// src/app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './navigation/navbar';
import Footer from './footer/page'; // Import the Footer component
import "@fortawesome/fontawesome-free/css/all.min.css"; // Import Font Awesome CSS
import "./globals.css";
import { CartProvider } from './context/CartContext'; // Import the CartProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
            integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMWSfGmW3GScd6g4vGI2C/4VpGV5zlh9Bl2J79j"
            crossOrigin="anonymous"
          />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar />
          {children}
          <Footer /> {/* Add the Footer component here */}
        </body>
      </html>
    </CartProvider>
  );
}
